- name: Make directories
  file:
    name: "{{item.name}}"
    owner: "{{item.owner}}"
    mode: "{{item.mode}}"
    state: "directory"
  with_items:
     - { name: "/home/pi/src/", owner: "pi", mode: "755" }
- name: Copy files
  copy: "{{item}}"
  become: "true"
  with_items:
     - { src: "opencv.zip", dest: "/home/pi/src/opencv.zip", owner: "pi", mode: "644" }
     - { src: "opencv_contrib.zip", dest: "/home/pi/src/", owner: "pi", mode: "644" }
     - { src: "pi_profile", dest: "/home/pi/.profile", owner: "pi", mode: "644" }
     - { src: "compile-opencv.sh", dest: "/home/pi/src/", owner: "pi", mode: "755" }     
     - { src: "dphys-swapfile", dest: "/etc/", owner: "root", mode: "644" }     
- name: Restart swap service
  become: true
  service:
    name: dphys-swapfile
    state: restarted
- name: Install packages
  become: yes
  apt:
    name: "{{item}}"
    state: "present"
  with_items:
    - build-essential
    - cmake
    - pkg-config
    - libjpeg-dev
    - libtiff5-dev
    - libjasper-dev
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - libv4l-dev
    - libxvidcore-dev
    - libx264-dev
    - libgtk2.0-dev
    - libgtk-3-dev
    - libgdk-pixbuf2.0-dev
    - libatlas-base-dev
    - gfortran
    - python2.7-dev
    - python3-dev
    - python-pip
    - python3-pip
    - python-virtualenv
    - python3-virtualenv
#    libcanberra-gtk*
#    - libpng12-dev
- name: Install pip packages
  become: yes
  pip:
    name: "{{item}}"
    state: "present"
  with_items:
    - virtualenvwrapper
- name: Prepare virtualenv
  pip:
    virtualenv: /home/pi/pyve/opencv
    name: "{{item}}"
    virtualenv_python: python3
  with_items:
    - numpy
    

